#%RAML 1.0 Library
usage:
traits:
  transcationId: !include traits/common Header trait.raml
  departureLocationcode: !include traits/queryparmdeslocationcode traits.raml
  destinationlocationcode: !include traits/queryparmdestination locationcode trait.raml